services:
  tts:
    build:
      context: .
      args:
        UNAME: ${UNAME}
        PUID: ${PUID}
        PGID: ${PGID}
    tty: true
    stdin_open: true
    entrypoint:
      - bash
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WORKSPACE_DIR=/data/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/src:rw
      - /home/${USER:-user}/Workspace:/data/workspace:rw
      - cache:/data/cache:rw
    restart: never
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - utility
                - compute
                - video

  codex:
    extends: tts
    profiles:
      - cli
    environment:
      - CODEX_HOME=/opt/codex
    entrypoint:
      - codex
      - --config
      - projects./src.trust_level=trusted
      - --search
      - --dangerously-bypass-approvals-and-sandbox
    volumes:
      - ./.codex-home:/opt/codex:rw

  claude:
    extends: tts
    profiles:
      - cli
    environment:
      - CLAUDE_MODEL=sonnet[1m]
    entrypoint:
      - claude
    volumes:
      - ./.codex-home:/home/${UNAME}/.claude:rw

volumes:
  cache:
    driver: local
