[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "laban-tts"
version = "0.1.0"
description = "Voice acting driven audiobook synthesis using LLM generated cue scripts."
readme = "README.md"
requires-python = ">=3.11"
authors = [
  { name = "Santu Mariani<santumariani@proton.me>" }
]
keywords = ["tts", "audiobook", "cue scripts", "laban profiles", "chatterbox-tts", "langchain"]
dependencies = [
  "loguru",
  "pydantic",
  "pydantic-xml",
  "langchain-core",
  "langchain-openai",
  "langchain-text-splitters",
  "tiktoken",
  "typer",
  "unstructured[md]",
  "pydub",
  "soundfile",
]

[dependency-groups]
dev = [
  "pytest",
  "pytest-datadir",
  "basedpyright",
  "ruff",
  "black",
]
dev-torch = [
  "torchaudio",
]
chatterbox = [
  "chatterbox-tts==0.1.6",
  "pykakasi==2.3.0",  
  # "pkuseg==0.0.25",
]

# [tool.uv.extra-build-dependencies]
# pkuseg = ["numpy"]

[project.scripts]
media-watchdog = "media_watchdog:main"


[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[tool.pyright]
pythonVersion = "3.12"
include = ["src", "scripts"]
typeCheckingMode = "standard"
enableTypeIgnoreComments = false
deprecateTypingAliases = false
reportUnnecessaryTypeIgnoreComment = "error"
strictListInference = true
strictDictionaryInference = true
strictSetInference = true

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint]
select = ["B009", "B010"]
